### ISSUE TITLE
Is there a way to add a new reference to the sequence database after MinVar is installed?

### ISSUE THREAD

**Issue by sschmutz** [ozagordi/MinVar#30]
Can (if yes, how?) one add a new reference to the sequence database after MinVar is installed via bioconda?

**Comment by sschmutz** [comment]
I guess not, right?

Instead did it like follows:
- create conda environment `conda create -n minvar_new python=3.5`
- install all dependencies listed below [`run:`](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/minvar/meta.yaml)
- clone repo `git clone https://github.com/ozagordi/MinVar.git`
- change references as described [here](https://minvar.readthedocs.io/en/latest/#add-a-new-reference-to-the-sequence-database)
- install MinVar from within the cloned repo `python setup.py install`

**Comment by ozagordi** [comment]
Correct.
Another option is to install with `pip install -e ./` instead of `python setup.py install`. `-e` stands for "install in editable mode" and should be equivalent to the development mode as in `python setup.py develop`. In this way the executables reads the source files right away so that the effect of any edit is immediately seen and one does not need to reinstall every time. Although I'm not sure, this should apply to data files like references as well.

Another advantage is that `pip` provides an uninstall, `pip uninstall minvar`.
